<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite_DemoWebShop</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c8c504f8-56ca-4830-8eeb-4a6395ef1577</testSuiteGuid>
   <testCaseLink>
      <guid>7d64477a-e43e-469e-9b69-f7753925e29e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test_DemoWebShop</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2f53df37-c562-4838-aa36-a52648905bbf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ItemData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2f53df37-c562-4838-aa36-a52648905bbf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>order</value>
         <variableId>884d3b1c-17dd-4472-848f-247d20980a70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2f53df37-c562-4838-aa36-a52648905bbf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemsWithQuantity</value>
         <variableId>644c50fd-8e5a-44d3-8ef8-e9ff41ffd227</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e4ae6d-5ea8-49c2-b43e-0bc4577a1d88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6788d836-54e6-4d23-adcf-cc8d5be5aa59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3110f6a-2362-4676-bc4f-6b8f42819655</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e8528bf-eb70-4bd6-a72b-49d2b6011041</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11b661cc-1913-40d7-a3f6-ead2b73e3dea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce8ad06d-ce07-4477-bf18-f526b16325c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ca83151-0ebd-429b-b948-d06629318b95</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
