#false.
#@USER username to access database.
#@PASSWORD encrypted password.
PASSWORD=NGdRM2xHdEFLOQ\=\=
SECURE_USER_ACCOUNT=true
CONNECTION_PROPERTIES={\n  "connectionProperty"\: [],\n  "props"\: {}\n}
USER=sql12829951
DRIVERCLASSNAME=
SHOW_WARNING=false
URL=jdbc\:mysql\://sql12.freesqldatabase.com/sql12829951
