<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_zipCode</name>
   <tag></tag>
   <elementGuidId>d2e47ff5-2c01-446f-a136-39d9867f77cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ZipPostalCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ZipPostalCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Zip / postal code:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1325e98f-9284-411c-9651-fa800d870b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zip-input</value>
      <webElementGuid>a2359fc7-ee47-43fe-9513-7200f7fba9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ZipPostalCode</value>
      <webElementGuid>9ad1498c-1b75-42a6-a444-1a4e2db6cad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ZipPostalCode</value>
      <webElementGuid>72eed3d0-f658-47ea-84e1-847f6d6cb3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d54e1921-f1b3-479d-b23b-29680c4569f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10098</value>
      <webElementGuid>d7350514-9016-42b1-8ebf-602214ac2668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ZipPostalCode&quot;)</value>
      <webElementGuid>a52a13d2-69b6-4fab-959e-f758dd3c60ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ZipPostalCode']</value>
      <webElementGuid>c1734f89-bcc5-4ec9-8036-dfbcb3a9e2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>d08aa37a-dbee-4c7c-a62c-9a4dd91bffa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ZipPostalCode' and @name = 'ZipPostalCode' and @type = 'text']</value>
      <webElementGuid>2d61ae20-63b9-4f1f-9260-9a9a355ae938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
